#!/bin/bash 
#SBATCH -J al-sym 
#SBATCH -q regular 
#SBATCH -N 4
#SBATCH -t 48:00:00
#SBATCH -C gpu
#SBATCH -G 16
#SBATCH -A m526_g 


# Load necessary modules
 module load nvidia/22.7 cray-hdf5-parallel/1.12.2.3 nccl/2.15.5-ofi cray-fftw/3.3.10.3 cudatoolkit/11.7 craype-accel-nvidia80 gpu/1.0 cray-libsci/23.02.1.1

# Run Swap.py to prepare the POSCAR file
python DFTMC.py



